// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cPiMH4jDRu-4yBnsW6rizG-6mwWcTGQ',
    appId: '1:593308414079:web:88b58709a24dd00bf88f4a',
    messagingSenderId: '593308414079',
    projectId: 'fahad1-819e4',
    authDomain: 'fahad1-819e4.firebaseapp.com',
    storageBucket: 'fahad1-819e4.firebasestorage.app',
    measurementId: 'G-Q0177Y8NNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDouEIPxGIQL2Ts5nYImpAPirmBDR0tlj4',
    appId: '1:593308414079:android:d1c01fa2dea3587af88f4a',
    messagingSenderId: '593308414079',
    projectId: 'fahad1-819e4',
    storageBucket: 'fahad1-819e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDvprUzKD-1UzfOu2dLqJxfZU3uXDqA8s',
    appId: '1:593308414079:ios:22630e1a5148f7fff88f4a',
    messagingSenderId: '593308414079',
    projectId: 'fahad1-819e4',
    storageBucket: 'fahad1-819e4.firebasestorage.app',
    iosClientId: '593308414079-t0bvdrechakjuleglkt49j9bhacm9qg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDvprUzKD-1UzfOu2dLqJxfZU3uXDqA8s',
    appId: '1:593308414079:ios:22630e1a5148f7fff88f4a',
    messagingSenderId: '593308414079',
    projectId: 'fahad1-819e4',
    storageBucket: 'fahad1-819e4.firebasestorage.app',
    iosClientId: '593308414079-t0bvdrechakjuleglkt49j9bhacm9qg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0cPiMH4jDRu-4yBnsW6rizG-6mwWcTGQ',
    appId: '1:593308414079:web:adfab7f644e2e5b2f88f4a',
    messagingSenderId: '593308414079',
    projectId: 'fahad1-819e4',
    authDomain: 'fahad1-819e4.firebaseapp.com',
    storageBucket: 'fahad1-819e4.firebasestorage.app',
    measurementId: 'G-17DKWJQN46',
  );

}